# Generated by Django 3.1.1 on 2020-11-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scienziato', models.ImageField(upload_to='cal/')),
                ('giorno', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=600)),
                ('link', models.CharField(max_length=600)),
                ('status', models.CharField(default='Non today', editable=False, max_length=10)),
            ],
            options={
                'verbose_name': 'Scienziato',
                'verbose_name_plural': 'Scienziati',
            },
        ),
    ]
