# Generated by Django 3.1.1 on 2020-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0002_auto_20201104_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='img_default',
            field=models.ImageField(help_text='Non hai ancora sbloccato questo scienziato', upload_to='cal/'),
            
        ),
        migrations.AlterField(
            model_name='calendario',
            name='giorno',
            field=models.CharField(help_text='DD, indicare il numero del giorno', max_length=2),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='link',
            field=models.CharField(blank=True, help_text='Quando è su instagram,  inserire il link al post', max_length=600),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='nome',
            field=models.CharField(help_text='Inserire il nome dello scienziato', max_length=600),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='scienziato',
            field=models.ImageField(help_text='Foto a colori dello scienziato', upload_to='cal/'),
        ),
    ]
