# Generated by Django 3.1.1 on 2020-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0003_auto_20201104_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'verbose_name': 'Virus', 'verbose_name_plural': 'Virus'},
        ),
        migrations.AlterField(
            model_name='calendario',
            name='link',
            field=models.CharField(blank=True, help_text='Quando è su instagram, inserire il link al post', max_length=600),
        ),
    ]
