# Generated by Django 3.1.1 on 2020-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome del design', max_length=600)),
                ('design', models.ImageField(help_text="Aggiungi l'immagine che del design", upload_to='designs/')),
                ('link_tshirt', models.CharField(blank=True, help_text='Quando è pronto il design inserire il link, inserire il link alla maglietta', max_length=600)),
                ('link_felpa', models.CharField(blank=True, help_text='Quando è pronto il design inserire il link, inserire il link alla felpa', max_length=600)),
                ('link_cover', models.CharField(blank=True, help_text='Quando è pronto il design inserire il link, inserire il link alla cover', max_length=600)),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Design',
            },
        ),
    ]
