# Generated by Django 3.1.1 on 2020-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(default='Non visibile', editable=False, max_length=10),
        ),
    ]
