# Generated by Django 3.1.1 on 2020-10-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0004_auto_20201030_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='esercizio',
            name='commento',
            field=models.TextField(default='try', help_text='Commentare il processo mentale che ha portato alla scelta di ciò che è stato caricato come "struttura" e nell\'eventuale meccanismo.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esercizio',
            name='grafico',
            field=models.ImageField(blank=True, help_text="Caricare un file .png/.svg/.jpeg contenente l'eventuale grafico necessario per la dimostrazione", upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='esercizio',
            name='meccanismo',
            field=models.ImageField(blank=True, help_text="Caricare un file .png/.svg/.jpeg contenente lo schema dell'eventuale meccanismo di reazione", upload_to='mech/'),
        ),
        migrations.AddField(
            model_name='esercizio',
            name='risoluzione',
            field=models.TextField(default='try', help_text='Scrivere la risoluzione del problema in maniera chiara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esercizio',
            name='risultato',
            field=models.TextField(default='try', help_text='Evidenziare il risultato ottenuto dalla risoluzione delle equazioni.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esercizio',
            name='strutture',
            field=models.ImageField(blank=True, help_text='Caricare un file .png/.svg/.jpeg contenente lo schema della reazione', upload_to='str/'),
        ),
    ]
