# Generated by Django 3.1.1 on 2020-10-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0005_auto_20201030_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Scrivere il testo del problema. Se si è utilizzato il bot che sfrutta la tecnologia OCR controllare la correttezza del teso ricevuto.')),
            ],
        ),
        migrations.CreateModel(
            name='ImmaginiTeoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('teoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercises.teoria')),
            ],
        ),
    ]
