# Generated by Django 3.1.1 on 2020-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0006_immaginiteoria_teoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='immaginiteoria',
            name='didascalita',
            field=models.TextField(default='try', help_text="Inserire una breve didascalia per l'immagine"),
            preserve_default=False,
        ),
    ]
