# Generated by Django 3.1.1 on 2020-10-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0007_immaginiteoria_didascalita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immaginiteoria',
            old_name='didascalita',
            new_name='didascalia',
        ),
    ]
