# Generated by Django 3.1.1 on 2020-10-31 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0008_auto_20201031_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='teoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercises.materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teoria',
            name='argomento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercises.argomento'),
            preserve_default=False,
        ),
    ]
