# Generated by Django 3.1.1 on 2020-10-31 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0009_auto_20201031_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teoria',
            options={'verbose_name': 'Teoria', 'verbose_name_plural': 'Teoria'},
        ),
        migrations.AddField(
            model_name='teoria',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teoria',
            name='slug',
            field=models.SlugField(help_text='NON MODIFICARE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teoria',
            name='status',
            field=models.CharField(default='Draft', editable=False, max_length=10),
        ),
    ]
