# Generated by Django 3.1.1 on 2020-10-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0010_auto_20201031_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esercizio',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='teoria',
            name='materia',
        ),
        migrations.AlterField(
            model_name='argomento',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argomenti', to='Exercises.materia'),
        ),
        migrations.AlterField(
            model_name='esercizio',
            name='argomento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esercizi', to='Exercises.argomento'),
        ),
        migrations.AlterField(
            model_name='immaginiteoria',
            name='teoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='Exercises.teoria'),
        ),
        migrations.AlterField(
            model_name='teoria',
            name='argomento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teoria', to='Exercises.argomento'),
        ),
    ]
