# Generated by Django 3.1.1 on 2020-11-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0012_auto_20201101_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmaginiArgomento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Aggingi un'immagine per rendere il testo più chiaro. Formati .png, .svg, .jpg", upload_to='img_theo/')),
                ('didascalia', models.TextField(help_text="Inserire una breve didascalia per l'immagine")),
            ],
        ),
        migrations.RemoveField(
            model_name='teoria',
            name='argomento',
        ),
        migrations.AddField(
            model_name='argomento',
            name='teoria',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImmaginiTeoria',
        ),
        migrations.DeleteModel(
            name='Teoria',
        ),
        migrations.AddField(
            model_name='immaginiargomento',
            name='teoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='Exercises.argomento'),
        ),
    ]
