# Generated by Django 3.1.1 on 2020-11-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0013_auto_20201101_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argomento',
            options={'verbose_name': 'Argomento', 'verbose_name_plural': 'Argomenti'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materie'},
        ),
    ]
