# Generated by Django 3.1.1 on 2020-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0014_auto_20201104_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esercizio',
            name='commento',
            field=models.TextField(blank=True, help_text='Commentare il processo mentale che ha portato alla scelta di ciò che è stato caricato come "struttura" e nell\'eventuale meccanismo.'),
        ),
    ]
